/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 f:\Desktop\Projects\Web\NoodleSushi.github.io\public\models\cartridge.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_1: THREE.Mesh
    Cube_2: THREE.Mesh
    Cube_3: THREE.Mesh
    Cube001: THREE.Mesh
  }
  materials: {
    Container: THREE.MeshStandardMaterial
    Design: THREE.MeshStandardMaterial
    Label: THREE.MeshStandardMaterial
    Outline: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cartridge.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.Outline} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials.Container} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials.Design} />
      <mesh geometry={nodes.Cube_3.geometry} material={materials.Label} />
    </group>
  )
}

useGLTF.preload('/cartridge.glb')
