/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 f:\Desktop\Projects\Web\NoodleSushi.github.io\public\models\cartridge.glb -t 
*/

import * as THREE from 'three';
import { useEffect, useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { MeshCollider } from '@react-three/rapier';
import { EventHandlers } from '@react-three/fiber/dist/declarations/src/core/events';

type GLTFResult = GLTF & {
  nodes: {
    Cube_1: THREE.Mesh
    Cube_2: THREE.Mesh
    Cube_3: THREE.Mesh
    Cube001: THREE.Mesh
  }
  materials: {
    Container: THREE.MeshStandardMaterial
    Design: THREE.MeshStandardMaterial
    Label: THREE.MeshStandardMaterial
    Outline: THREE.MeshStandardMaterial
  }
  animations: []
}

const designLookup = new Map<string, THREE.MeshStandardMaterial>();

export function CartridgeModel(props: JSX.IntrinsicElements['group'] & { img: string, outline: boolean | undefined, onPointerEnter: EventHandlers['onPointerEnter'], onPointerLeave: EventHandlers['onPointerLeave'] }) {
  const { nodes, materials } = useGLTF('./models/cartridge.glb') as GLTFResult;

  const [designMaterial, setDesignMaterial] = useState<THREE.MeshStandardMaterial>(materials.Design);
  const labelMaterialRef = useRef<THREE.MeshStandardMaterial>(materials.Label);

  useEffect(() => {
    if (!designLookup.has(props.img)) {
      const newMat: THREE.MeshStandardMaterial = designMaterial.clone();
      newMat.map = new THREE.TextureLoader().load(props.img);
      newMat.map.flipY = false;
      newMat.emissiveMap = new THREE.TextureLoader().load(props.img);
      newMat.emissiveMap.flipY = false;
      newMat.needsUpdate = true;
      designLookup.set(props.img, newMat);
    }

    setDesignMaterial(designLookup.get(props.img) as THREE.MeshStandardMaterial);
    labelMaterialRef.current = designLookup.get(props.img) as THREE.MeshStandardMaterial;
  }, [props.img, designMaterial]);

  
  return (
    <group castShadow receiveShadow {...props} dispose={null} scale={[0.25, 0.25, 0.25]}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.Outline} visible={props.outline} />
      <MeshCollider type="cuboid">
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Container} onPointerEnter={props.onPointerEnter} onPointerLeave={props.onPointerLeave} castShadow receiveShadow/>
      </MeshCollider>
      <mesh geometry={nodes.Cube_2.geometry} material={designMaterial} />
      <mesh geometry={nodes.Cube_3.geometry} material={labelMaterialRef.current} />
    </group>
  );
}

useGLTF.preload('./models/cartridge.glb');
